[book]
authors = ["rust-lang.xfoss.com"]
language = "zh"
multilingual = false
src = "src"
title = "打赏，donate - buy me a coffee"

[preprocessor.last-changed]
command = "mdbook-last-changed"
renderer = ["html"]


[output.html]

[output.html.print]
enable = false

[output.html.search]
enable = false

